- name: Build ubuntu and centos docker images
  hosts: localhost
  ignore_errors: yes
  tasks:

   - name: Remove all existing containers
     shell: docker rm -f $(docker ps -aq) 

   - name: Remove the existing ansible ubuntu docker image
     shell:  docker rmi tektutor/ansible-ubuntu

   - name: Build Ubuntu ansible image
     docker_image:
        name: "tektutor/ansible-ubuntu"
        state: build
        dockerfile: UbuntuDockerfile
        path: .
